name: CI/CD

on:
  push:
    branches: [ "main", "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Deploy Staging
      if: github.ref == 'refs/heads/staging'
      run: echo "Deploy staging..."

    - name: Deploy Production
      if: github.ref == 'refs/heads/main'
      run: echo "Deploy produção..."