name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build

    - name: Build Docker Image
      run: docker build -t wastemanagement .

    - name: Deploy Staging
      run: echo "Deploy realizado em STAGING"

    - name: Deploy Production
      run: echo "Deploy realizado em PRODUÇÃO"